use_frameworks!

target 'MyPaster_Example' do
  pod 'MyPaster', :path => '../'

  target 'MyPaster_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
